name: check-rs

on:
  pull_request:


jobs:
  install-protoc: 
    name: intsall protoc
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  lint-format-test:
    name: lint, format, spell check, test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install toolchain
        run: |
          exit -1

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run Cargo Check
        run: cargo check --workspace --all-targets --release --locked

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-targets -- -D warnings

      - name: Run test
        # We need to install sass first to enable sass-loader
        run: |
          node -e "console.log(process.arch)"
          cargo test --workspace  -- --nocapture --test-threads=1

      - name: The step only run the job is failed.
        uses: andymckay/cancel-action@0.3
        if: ${{ !success() }}
